OnlineShopWebApp/Models/Order_ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using OnlineShop.Db.Models;

namespace OnlineShopWebApp.Models
{
    public class Order_ViewModels
    {
        public Guid Id { get; set; }
        public List<CartItem> CartItems { get; set; }
        public UserDeleveryInfo UserDeleveryInfo { get; set; }
        public DateTime CreateDateTime { get; set; }
        public OrderStatus Status { get; set; }
        public string BuyerLogin { get; set; }
        public decimal FullCost()
        {
            decimal fullCost = 0;
            foreach (var cartItem in CartItems)
            {
                fullCost += cartItem.Product.Cost * cartItem.Count;
            }
            return fullCost;
        }

    }
}

OnlineShopWebApp/Areas/Admin/Controllers/OrdersController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Interfase;
using OnlineShop.Db.Models;
using OnlineShopWebApp.Filters;
using OnlineShopWebApp.Helpers;
using OnlineShopWebApp.Interfase;
using OnlineShopWebApp.Models;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [ServiceFilter(typeof(CheckingForAuthorization))]
    public class OrdersController : Controller
    {
        private readonly IOrdersRepositiry _ordersRepositiry;
        public OrdersController(IOrdersRepositiry ordersRepositiry)
        {
            _ordersRepositiry = ordersRepositiry;
        }
        public IActionResult Index()
        {
            var orders = _ordersRepositiry.GetAll();
            var ordersVM = orders.Select(x => Mapping.ToOrder_ViewModel(x)).ToList();
            return View(ordersVM);
        }
        public IActionResult Details(Guid orderId)
        {
            var orders = _ordersRepositiry.GetAll();
            
            var order = orders.Find(order => order.Id == orderId);
            var orderVM = Mapping.ToOrder_ViewModel(order);
            return View(orderVM);
        }
        [HttpPost]
        public IActionResult SaveDetails(Order newOrder)
        {
            _ordersRepositiry.UpdateOrderStatus(newOrder);
            var orderId = newOrder.Id;
            return RedirectToAction("Details", new { orderId });
        }
    }
}

OnlineShopWebApp/Controllers/OrderController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Interfase;
using OnlineShop.Db.Models;
using OnlineShopWebApp.Filters;
using OnlineShopWebApp.Helpers;
using OnlineShopWebApp.Interfase;
using OnlineShopWebApp.Models;

namespace OnlineShopWebApp.Controllers
{
    [ServiceFilter(typeof(CheckingForAuthorization))]
    public class OrderController : Controller
    {
        private readonly IOrdersRepositiry _ordersRepositiry;
        private readonly ICartsRepository _cartsRepository;
        private readonly IUsersManager _usersManager;
        public OrderController(IOrdersRepositiry ordersRepositiry, IUsersManager usersManager, ICartsRepository cartsRepository)
        {
            _ordersRepositiry = ordersRepositiry;
            _usersManager = usersManager;
            _cartsRepository = cartsRepository;
        }

        public IActionResult Index()
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            var cart = _cartsRepository.Find(buyerLogin);
            return View(Mapping.ToCart_ViewModel(cart));
        }

        [HttpPost]

        public IActionResult RewriteInfoBuying()
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            _cartsRepository.ClearInfoBuying(buyerLogin);
            return RedirectToAction("Index", new {buyerId = buyerLogin });
        }

        [HttpPost]

        public IActionResult RewriteInfoBuying(UserDeleveryInfo_ViewModels userDeleveryInfoViewModels)
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            var userDelevery = Mapping.ToUserDeleveryInfo(userDeleveryInfoViewModels);
            _cartsRepository.ClearInfoBuying(buyerLogin);
            return RedirectToAction("Index", new { buyerId = buyerLogin });
        }

        [HttpPost]
        public IActionResult BuyValid(UserDeleveryInfo userDeleveryInfo)
        {
            userDeleveryInfo.Id = Guid.NewGuid();
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            if (ModelState.IsValid)
            {
                _cartsRepository.SaveInfoBuying(userDeleveryInfo, buyerLogin);
                return RedirectToAction("Buy", new {buyerId = buyerLogin });
            }
            return Content("errorValid");
        }
        public IActionResult Buy()
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            _ordersRepositiry.Buy(buyerLogin);
            return View();
        }
    }
}

OnlineShopWebApp/Views/Order/Buy.cshtml
@{
    ViewData["Title"] = "Отчет об оформлении заказа";
}

<div class="text-center">
    <h2 class="display-5 Title_sile">Заказ выполнен удачно</h2>
    <p></p>
</div>

<a class="btn btn-outline-dark text-nowrap btn-sm mx-1 my-1 text-center" asp-area="" asp-controller="Home" asp-action="Index" role="button">Продолжить покупки</a>

OnlineShopWebApp/Views/Order/Index.cshtml
@model Cart_ViewModel
@{
    ViewData["Title"] = "Оформление заказа";
}


<div class="text-center">
    <h1 class="display-5 Title_sile">Оформление заказа</h1>
    <p></p>
</div>


<p>
    @if (Model.UserDeleveryInfo == null)
    {
        <a class="btn btn-outline-danger text-nowrap"
           data-toggle="collapse"
           href="#collapseExample"
           role="button"
           aria-expanded="false"
           aria-controls="collapseExample">
            Заполнить данные о заказчике
        </a>
    }
    else
    {
        <a class="btn btn-outline-danger text-nowrap"
           data-toggle="collapse"
           href="#collapseExample"
           role="button"
           aria-expanded="false"
           aria-controls="collapseExample">
            Проверить данные о заказчике
        </a>
    }

</p>
<form method="post" asp-controller="Order" asp-action="BuyValid">
    <div class="was-validated" asp-validation-summary="All"></div>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            @await Component.InvokeAsync("InfoBuying")
        </div>
    </div>

    <h6>Список приобретаемых товаров:</h6>
    <h6>Пожалуйста, выберите дополнительные опции, если это необходимо</h6>
    @await Html.PartialAsync("FormCheque", Model.CartItems)


    <button type="submit"  class="btn btn-outline-dark text-nowrap col-3 mx-0 my-3" asp-area="" asp-controller="Order" asp-action="BuyValid" role="button">Отправить заявку</button>
</form>