OnlineShopWebApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Models;
using OnlineShopWebApp.Interfase;
using OnlineShopWebApp.Models;

namespace OnlineShopWebApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUsersManager _usersManager;
        public LoginController(IUsersManager usersManager)
        {
            _usersManager = usersManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(UserAutorized userInput)
        {
            var user = _usersManager?.Find(userInput.Login);
            if (user == null)
            {
                ModelState.AddModelError("", "Такого аккаунта не существует");
            }
            else if (userInput?.Password != user?.Password)
            {
                ModelState.AddModelError("", "Логин или пароль введён неверно");
            }
            if (ModelState.IsValid)
            {
                _usersManager.Authorized(userInput);
                return RedirectToAction(actionName:"Index",controllerName: "User");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Register(UserRegistration userInput)
        {
            if (userInput.Login == userInput.Password)
            {
                ModelState.AddModelError("", "Логин и пароль не должны совпадать!");
            }
            if (_usersManager.Find(userInput.Login) != null)
            {
                ModelState.AddModelError("", "Такой аккаунт уже существует");
            }
            if (ModelState.IsValid)
            {
                _usersManager.Add(userInput);
                return RedirectToAction("Index", "User");
            }
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult TabooAccess()
        {
            return View();
        }

        public IActionResult Exit()
        {
            _usersManager.Exit();
            return RedirectToAction("Index");
        }
    }
}

OnlineShopWebApp/Views/Login/Index.cshtml
@model UserAutorized
@{
    ViewData["Title"] = "Авторизация";
}

<form method="post" asp-controller="Login" asp-action="Index">
    <div class="container">
        <div class="was-validated" asp-validation-summary="All"></div>
        <h3 class="display-5 text-center">Вход</h3>
        <p></p>
        <div class="form-group col-md-3 mx-auto">
            <label asp-for="Login" class="text-center">Логин</label>
            <input type="text" class="form-control" id="Input1" placeholder="Логин" required="" name="Login" asp-for="Login"/>
            <span asp-validation-for="Login"></span>
        </div>
        <p></p>
        <div class="form-group  col-md-3 mx-auto">
            <label asp-for="Password" class="text-center">Пароль</label>
            <input type="password" class="form-control" id="Input2" placeholder="Пароль" name="Password" required="" asp-for="Password"/>
            <span asp-validation-for="Password"></span>

        </div>
        <div class="row  col-md-3 mx-auto">
            <div class="form-check col-1">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
            </div>
            <div class="col">Запомнить меня?</div>
        </div>
        <p></p>
        <div class="col-md-1 mx-auto">
            <button type="submit" class="btn btn-outline-dark text-center"  asp-controller="Login" asp-action="Index" asp-route-userInput="@Model">Войти</button>
        </div>
    </div>
</form>
<p></p>
<div class="col-md-3 mx-auto">
    <a class="btn btn-light text-center" asp-controller="Login" asp-action="Register">Регистрация нового пользователя</a>
</div>

OnlineShopWebApp/Views/Login/Register.cshtml
@model UserRegistration

@{
    ViewData["Title"] = "Регистрация";
}

<form method="post" asp-controller="Login" asp-action="Register">
    <div class="container">
        <div class="was-validated" asp-validation-summary="All"></div>
        <h3 class="display-5 text-center">Регистрация</h3>
        <p></p>
        <div class="form-group col-md-3 mx-auto">
            <label asp-for="Login" class="text-center">Логин</label>
            <input type="text" class="form-control" id="Input1" placeholder="Логин" required="" name="Login" asp-for="Login"/>
            <span asp-validation-for="Login"></span>
        </div>
        <p></p>
        <div class="form-group  col-md-3 mx-auto">
            <label asp-for="Password" class="text-center">Пароль</label>
            <input type="password" class="form-control" id="Input2" placeholder="Пароль" required="" name="Password" asp-for="Password"/>
            <span asp-validation-for="Password"></span>
        </div>
        <div class="form-group  col-md-3 mx-auto">
            <label asp-for="PasswordConfirm" class="text-center">Повтор пароля</label>
            <input type="password" class="form-control" id="lInput3" placeholder="Подтвердите пароль" required="" name="PasswordConfirm" asp-for="PasswordConfirm"/>
            <span asp-validation-for="PasswordConfirm"></span>
        </div>
        <p></p>
        <div class="col-md-3 mx-auto">
            <button type="submit" class="btn btn-outline-dark text-center" asp-controller="Login" asp-action="Register">Зарегестрироваться</button>
        </div>
    </div>
</form>

OnlineShopWebApp/Views/Login/TabooAccess.cshtml
@{
    ViewData["Title"] = "Запрет доступа";
}

<div class="text-center">
    <h2 class="display-5 Title_sile">Вам запрещён доступ в данный раздел</h2>
    <p></p>
</div>

<a class="btn btn-outline-dark text-nowrap btn-sm mx-1 my-1 text-center" asp-area="" asp-controller="Home" asp-action="Index" role="button">На главную страницу</a>