OnlineShopWebApp/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopWebApp.Interfase;
using System;
using OnlineShop.Db.Interfase;
using OnlineShopWebApp.Filters;
using OnlineShopWebApp.Helpers;

namespace OnlineShopWebApp.Controllers
{
    [ServiceFilter(typeof(CheckingForAuthorization))]
    public class CartController : Controller
    {
        private readonly ICartsRepository _cartsRepository;
        private readonly IUsersManager _usersManager;
        public CartController(IUsersManager usersManager, ICartsRepository cartsRepository)
        {
            _usersManager = usersManager;
            _cartsRepository = cartsRepository;
        }
        public IActionResult Index()
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            var cart = _cartsRepository.Find(buyerLogin);
            if (cart == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var cartVM = Mapping.ToCart_ViewModel(cart);
            return View(cartVM);
        }

        public IActionResult AddProduct(Guid productId)
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            _cartsRepository.AddProduct(productId, buyerLogin);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteProduct(Guid productId)
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            _cartsRepository.DeleteProductInCart(productId, buyerLogin);
            return RedirectToAction("Index");
        }

        public IActionResult ReduceDuplicateProduct(Guid productId)
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            _cartsRepository.ReduceDuplicateProductCart(productId, buyerLogin);
            return RedirectToAction("Index");
        }

        public IActionResult Clear()
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            _cartsRepository.ClearCart(buyerLogin);
            return RedirectToAction("Index");
        }
    }


}

OnlineShopWebApp/Controllers/FavoriteController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Interfase;
using OnlineShopWebApp.Helpers;
using OnlineShopWebApp.Interfase;

namespace OnlineShopWebApp.Controllers
{

    public class FavoriteController : Controller
    {
        private readonly IUsersManager _usersManager;
        private readonly IProductRepository _productRepository;
        private readonly IFavoriteRepository _favoriteRepository;
        public FavoriteController(IProductRepository productRepository, IFavoriteRepository favoriteRepository, IUsersManager usersManager)
        {
            _usersManager = usersManager;
            _productRepository = productRepository;
            _favoriteRepository = favoriteRepository;
        }

        public IActionResult Index()
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            var products = _favoriteRepository.GetAll(buyerLogin);
            return View(Mapping.ToProduct_ViewModels(products));
        }
        public IActionResult Add(Guid productId)
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            var product = _productRepository.Find(productId);
            _favoriteRepository.Add(buyerLogin, product);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Remove(Guid productId)
        {
            var buyerLogin = _usersManager.GetLoginAuthorizedUser();
            _favoriteRepository.Remove(buyerLogin, productId);
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineShopWebApp/Controllers/ProductController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Interfase;
using OnlineShopWebApp.Models;

namespace OnlineShopWebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        public ProductController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public IActionResult Index(Guid productId)
        {

            var product = _productRepository.Find(productId);
            var productViewModels = new Product_ViewModel
            {
                Id = product.Id,
                CodeNumber = product.CodeNumber,
                Cost = product.Cost,
                Description = product.Description,
                Images = product.Images,
                Length = product.Length,
                Square = product.Square,
                Width = product.Width
            };
            return View(productViewModels);
        }
    }
}

OnlineShopWebApp/Views/Favorite/Index.cshtml
@model List<Product_ViewModel>
@{
    ViewData["Title"] = "Список продуктов в избранном";
}

<div class="text-center">
    <h1 class="display-5">Список продуктов в избранном</h1>
    
</div>
<div class="row g-10">
    @foreach (var product in Model)
    {
        <div class="col-3 card shadow">
            <h5></h5>
            <img class="card-img-top text-sm-right" src="image/@product.Images">
            <div class="card-body ">
                <a stile="color:black" 
                       asp-area="" 
                       asp-controller="Product" 
                       asp-action="Index" 
                       asp-route-productId="@product.Id">
                    <h5>№@product.CodeNumber</h5>
                </a>
                <h5>@product.Cost руб</h5>
                <div class="row">
                    <a class="btn btn-outline-dark text-nowrap btn-sm mx-1 my-1"
                       asp-area="" 
                       asp-controller="Comparison" 
                       asp-action="Add" 
                       asp-route-productId="@product.Id"
                       role="button">
                        В сравнение
                    </a>
                    <p >   </p>
                    <a class="btn btn-outline-dark text-nowrap btn-sm mx-1 my-1"
                       asp-area="" 
                       asp-controller="Cart" 
                       asp-action="AddProduct" 
                       asp-route-productId="@product.Id"
                       role="button">
                        <img src="/image/cartAdd.svg" width="20" height="20">
                    </a>
                    <a class="btn btn-outline-danger text-nowrap btn-sm mx-1 my-1"
                       asp-area="" 
                       asp-controller="Favorite" 
                       asp-action="Remove" 
                       asp-route-productId="@product.Id"
                       role="button">
                        <img src="/image/favoriteRemove.svg" width="20" height="20">
                    </a>
                </div>

            </div>
        </div>
    }
</div>